// lib/nav.js — COMPLETO. Todos los módulos del menú.

import dynamic from 'next/dynamic'

export const MODULE_ROUTES = {
  listado_consorcios:       dynamic(() => import('../modules/consorcio/ListadoConsorcios'), { ssr: false }),
  unidades:                 dynamic(() => import('../modules/unidades/Unidades'), { ssr: false }),
  copropietarios:           dynamic(() => import('../modules/copropietarios/Copropietarios'), { ssr: false }),
  cta_corriente:            dynamic(() => import('../modules/unidad/CtaCorriente'), { ssr: false }),
  reclamos:                 dynamic(() => import('../modules/unidad/Reclamos'), { ssr: false }),
  cert_libre_deuda:         dynamic(() => import('../modules/unidad/CertificadoLibreDeuda'), { ssr: false }),
  rendicion_cuentas:        dynamic(() => import('../modules/expensas/RendicionCuentas'), { ssr: false }),
  liquidacion:              dynamic(() => import('../modules/expensas/LiquidacionPeriodo'), { ssr: false }),
  expensas:                 dynamic(() => import('../modules/expensas/Expensas'), { ssr: false }),
  periodos:                 dynamic(() => import('../modules/expensas/ControlPeriodos'), { ssr: false }),
  historial_liquidaciones:  dynamic(() => import('../modules/expensas/HistorialLiquidaciones'), { ssr: false }),
  verificacion_unidades:    dynamic(() => import('../modules/expensas/VerificacionUnidades'), { ssr: false }),
  cobranzas:                dynamic(() => import('../modules/cobranzas/Cobranzas'), { ssr: false }),
  cobranzas_auto:           dynamic(() => import('../modules/cobranzas/CobranzasAutomaticas'), { ssr: false }),
  generar_debito:           dynamic(() => import('../modules/cobranzas/GenerarDebito'), { ssr: false }),
  anular_cobranza:          dynamic(() => import('../modules/cobranzas/AnularCobranzas'), { ssr: false }),
  mora_diferencial:         dynamic(() => import('../modules/cobranzas/MoraDiferencial'), { ssr: false }),
  morosos:                  dynamic(() => import('../modules/cobranzas/Morosos'), { ssr: false }),
  recibos:                  dynamic(() => import('../modules/cobranzas/ReciboPago'), { ssr: false }),
  proveedores:              dynamic(() => import('../modules/proveedores/Proveedores'), { ssr: false }),
  comprobantes:             dynamic(() => import('../modules/proveedores/Comprobantes'), { ssr: false }),
  pagos_prov:               dynamic(() => import('../modules/proveedores/PagosProveedor'), { ssr: false }),
  cta_proveedor:            dynamic(() => import('../modules/proveedores/CtaProveedor'), { ssr: false }),
  sueldos:                  dynamic(() => import('../modules/contabilidad/Sueldos'), { ssr: false }),
  cuentas_banco:            dynamic(() => import('../modules/contabilidad/CuentasBancarias'), { ssr: false }),
  mov_entre_cuentas:        dynamic(() => import('../modules/contabilidad/MovEntrecuentas'), { ssr: false }),
  mov_varios:               dynamic(() => import('../modules/contabilidad/MovimientosVarios'), { ssr: false }),
  movimientos:              dynamic(() => import('../modules/contabilidad/MovimientosUnidad'), { ssr: false }),
  reporte_movimientos:      dynamic(() => import('../modules/reportes/ReporteMovimientos'), { ssr: false }),
  estado_financiero:        dynamic(() => import('../modules/reportes/EstadoFinanciero'), { ssr: false }),
  balance_anual:            dynamic(() => import('../modules/reportes/BalanceAnual'), { ssr: false }),
  asambleas:                dynamic(() => import('../modules/comunicaciones/Asambleas'), { ssr: false }),
  emails:                   dynamic(() => import('../modules/comunicaciones/EnviarEmails'), { ssr: false }),
  notificacion:             dynamic(() => import('../modules/comunicaciones/EnviarNotificacion'), { ssr: false }),
  consultar_enviados:       dynamic(() => import('../modules/comunicaciones/ConsultarEnviados'), { ssr: false }),
  email_tracking:           dynamic(() => import('../modules/comunicaciones/EmailTracking'), { ssr: false }),
  agenda_venc:              dynamic(() => import('../modules/comunicaciones/AgendaVencimientos'), { ssr: false }),
  grupos_liquidacion:       dynamic(() => import('../modules/configuracion/GruposLiquidacion'), { ssr: false }),
  importar:                 dynamic(() => import('../modules/configuracion/ImportarExcel'), { ssr: false }),
  importar_pdf:             dynamic(() => import('../modules/configuracion/ImportarPDF'), { ssr: false }),
  equipo:                   dynamic(() => import('../modules/configuracion/Equipo'), { ssr: false }),
  perfil:                   dynamic(() => import('../modules/configuracion/PerfilAdmin'), { ssr: false }),
  plan_cuentas:             dynamic(() => import('../modules/contabilidad/PlanCuentas'), { ssr: false }),
  clientes:                 dynamic(() => import('../modules/superadmin/ClientesGASP'), { ssr: false }),
}
